files:
  include: '**/*.scss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-css-comments: 2
  no-debug: 2
  no-disallowed-properties: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 2
  no-mergeable-selectors: 2
  no-misspelled-properties:
    - 2
    - extra-properties: [-moz-filter]
  no-trailing-whitespace: 2
  no-trailing-zero: 2
  no-url-domains: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2
  property-units:
    - 2
    - global:
        - ch
        - em
        - ex
        - rem
        - cm
        - in
        - mm
        - pc
        - pt
        - px
        - q
        - vh
        - vw
        - vmin
        - vmax
        - deg
        - grad
        - rad
        - turn
        - ms
        - s
        - Hz
        - kHz
        - dpi
        - dpcm
        - dppx
        - '%'
      per-property: {}


  # Nesting
  declarations-before-nesting: 2

  # Name Formats
  function-name-format: 2
  mixin-name-format: 2
  placeholder-name-format: 2
  variable-name-format: 2

  # Style Guide
  bem-depth: 2
  border-zero: 2
  brace-style: 2
  clean-import-paths: 2
  hex-length: 2
  hex-notation: 2
  indentation: 2
  leading-zero: 2
  nesting-depth:
    - 2
    - max-depth: 4
  property-sort-order: 2
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Item
  final-newline: 2
